### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by VeeraAndroid** [lopspower/CircleView#2]
Hi, 

I need circle center transparent stoke and shadow only colors.
Can you make rectangular view like this. (center transparent stoke and shadow only colors)

**Comment by lopspower** [comment]
Hi, check [CircleView.kt](https://github.com/lopspower/CircleView/blob/master/circleview/src/main/java/com/mikhaellopez/circleview/CircleView.kt) and replace `canvas.drawCircle` by `canvas.drawRect`
