### ISSUE TITLE
Consider allowing inflating the CircleView from code

### ISSUE THREAD

**Issue by curioustechizen** [lopspower/CircleView#3]
`CircleView` only overrides one constructor: the one that expects both a `Context` and an `AttributeSet`. This makes it such that this view can only be used from XML.

If you want to create a new instance in code (`val circleView = CircleView(context)`) you cannot do it since AttributeSet is non-nullable.

Consider making AttributeSet nullable. Inside `private fun init(context: Context, attrs: AttributeSet)` you already set a default value for every attribute. You could extend the logic to also set the default values if attrs is null.

I could take a stab at opening a PR with this change if you give me the green signal.

**Comment by curioustechizen** [comment]
Just as a follow-up, I realized that the following line will never return null:

```kotlin
val attributes = context.obtainStyledAttributes(attrs, R.styleable.CircleView, 0, 0)
```

So, the change I requested is pretty trivial.

**Comment by lopspower** [comment]
Your update on pull request is now available on the last version:

```groovy
implementation 'com.mikhaellopez:circleview:1.3.2'
```

Thanks for your contribution
