### ISSUE TITLE
Bintray Shutdown. Migrate library to another host

### ISSUE THREAD

**Issue by scottymack** [lopspower/CircleView#7]
JFrog announced that they'll be shutting down JCenter:
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

Key dates are:

February 28th: No more submissions will be accepted to Bintray, JCenter
May 1st: Bintray, JCenter services will no longer be available
Hence CircleView should also be migrated to another maven repository like Maven central.

**Comment by developer-dxn** [comment]
Yes please migrate to other maven repository.

**Comment by lopspower** [comment]
Sorry for the delay 🙏
The version 1.4.0 is now available on MavenCentral :
```groovy
implementation 'com.mikhaellopez:circleview:1.4.0'
```
